import type { Metadata } from 'next'
import '../_src/scss/styles.scss';
import HamburgerNavigation from '@/_src/components/composites/hamburger-navigation/hamburger-navigation';
import { HamburgerItemsSampleContext } from '@/_src/components/composites/hamburger-navigation/components/hamburger-items/hamburger-items_sample.context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // debug code
  console.log("render layout.tsx");

  return (
    <html lang="en">
      {/* 
        components can be chosen from,
        theme--default,
        theme-cool,
        theme--hot.
        See _src/_scss/_custom_properties.scss
       */}
      <body className="theme--cool">
        <main>
          <HamburgerNavigation
            linkItems={HamburgerItemsSampleContext}
          />
          {children}
        </main>
      </body>
    </html>
  )
}
